# -*- coding: utf-8 -*-
"""sys_operations

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x5vvJqgClXlzAExK2NeefGec-NlkxZWE
"""

# Lab 9 - import module os and sys
import os
import sys
import platform
import socket

# Lab 9 - Practicing System Operations
print("- Practicing System Operations - ")
print("Current machine type")
print(platform.machine())
print("---------------------------------")
print("Current processor type")
print(platform.processor())
#question4 
print("---------------------------------")
print('Platform architecture:', platform.architecture())
print("---------------------------------")
print('Systems network name:', platform.node())
print("---------------------------------")
print("Set timeout time of Socket in seconds")
print(socket.setdefaulttimeout(50))
print("---------------------------------")
print("Default timeout of Socket ")
print(socket.getdefaulttimeout())
print("---------------------------------")
print("Operating system name: ")
print(os.name)
print("---------------------------------")
print("Current process ID (different for each person): ")
print(os.getpid())
print("---------------------------------")
print("Current process's child's process id ")
# Parent process to fork a child process
# 1. Create a new child process (under the hierarchyof the parent)
# 2. Copies ALL the code from the parent process to the child process
# 3. Both processes are going to run AT THE SAME TIME
# print(os.fork())
print("---------------------------------")


# Lab 9 - Using File Descriptor open
fd = os.open("fdpractice.txt", os.O_RDWR | os.O_CREAT)
print("File Descriptor number for fdpractice.txt: " + str(fd))
print("---------------------------------")

# Lab 9 - Read and Write to a file object
file_descriptor = os.open("fdpractice.txt",os.O_RDWR | os.O_CREAT)
print(file_descriptor)
print("------")
fo_TextIO = os.fdopen(file_descriptor,"w+")
fo_TextIO.write("Some string to write as file object")
fo_TextIO.flush()
os.lseek(file_descriptor,0,0)
print(os.read(file_descriptor,100))
print("----")
# Lab 9 - The code block runs twice because we have forked the process, and the child is also running the same code
sys.exit()

from google.colab import drive
drive.mount('/content/drive')

import sys

print("Python version")
print (sys.version)
print("-----------")
print("Version info.")
print (sys.version_info)